// Generated by `npm run report` (scripts/build-report.mjs). Do not edit by hand.
// Sizes are KB gzipped (the font is already compressed).
export const buildReport = {
  "measuredOn": "2026-09-25",
  "commit": "edbac29",
  "routes": 8,
  "sizes": {
    "homeInitialJs": 116,
    "homeAllJs": 140.5,
    "budget": 150,
    "elementJs": 49.4,
    "css": 7.1,
    "font": 35.4
  },
  "unit": {
    "passed": 8
  },
  "e2e": {
    "passed": 150,
    "skipped": 4,
    "flaky": 0
  },
  "lighthouse": [
    {
      "path": "/",
      "performance": 96,
      "accessibility": 100,
      "bestPractices": 100,
      "seo": 100
    },
    {
      "path": "/work/event-driven",
      "performance": 98,
      "accessibility": 100,
      "bestPractices": 100,
      "seo": 100
    }
  ]
};
